import { Router, type IRouter, type Request, type Response } from "express";
import { readFileSync } from "fs";
import { resolve } from "path";
import healthRouter from "./health";
import authRouter from "./auth";
import tenantsRouter from "./tenants";
import appsRouter from "./apps";
import usersRouter from "./users";
import kanbanRouter from "./kanban/index";
import orcamentoRouter from "./orcamento/index";
import comunidadeRouter from "./comunidade/index";
import billingRouter from "./billing/index";
import chatRouter from "./chat/index";
import suporteRouter from "./suporte";
import custosOrcamentosRouter from "./custos-orcamentos/index";
import custosFichasRouter from "./custos-fichas/index";
import storageRouter from "./storage";
import relatoriosRouter from "./relatorios/index";
import parceirosRouter from "./parceiros";
import webhooksVhsysRouter from "./webhooks-vhsys";
import plmRouter from "./plm/index";
import feedbackRouter from "./feedback";
import mentorRouter from "./mentor/index";
import operationalEventsRouter from "./operational-events";
import atosRouter from "./atos/index";
import marketingRouter from "./marketing/index";
import athosMemoryRouter from "./athos-memory/index";
import metaRouter from "./meta";
import assistantRouter from "./assistant/index";
import modaConectaRouter from "./moda-conecta/index";
import internalMarketingRouter from "./internal/marketing";
import internalCrmRouter from "./internal/crm";
import internalLeadsRouter from "./internal/leads";
import internalAutomationRouter from "./internal/automation";
import internalLeadHandoffRouter from "./internal/lead-handoff";
import internalGrowthRouter from "./internal/growth";
import internalCreativeImageRouter from "./internal/creative-image";
import internalLeadContextRouter from "./internal/lead-context";
import internalZapiWebhookRouter from "./internal/zapi-webhook";
import internalZapiCaptureRouter from "./internal/zapi-capture";
import internalLeadClassifyRouter from "./internal/lead-classify";
import internalLeadConversationStateRouter from "./internal/lead-conversation-state";
import internalZapiPollStateRouter from "./internal/zapi-poll-state";
import internalGptMakerRouter from "./internal/gptmaker";
import gptmakerWebhookRouter from "./internal/gptmaker-webhook";
import internalFidelizacaoRouter from "./internal/fidelizacao";
import internalMetaSendRouter from "./internal/meta-send";
import publicR2pbFormRouter from "./public/r2pb-form";
import publicR2pbOperacionalRouter from "./public/r2pb-operacional";
import publicFornecedorPageRouter from "./public/fornecedor-page";
import internalR2pbLookupRouter from "./internal/r2pb-lookup";
import internalR2pbZapiCheckRouter from "./internal/r2pb-zapi-check";
import internalJourneyRouter from "./internal/journey";
import internalAgentHandoffsRouter from "./internal/agent-handoffs";
import texintelRouter from "./texintel";
import publicParceiroFormRouter from "./public/parceiro-form";
import publicRhFormRouter from "./public/rh-form";
import parceirosCrudRouter from "./internal/parceiros-crud";
import cotacoesRouter from "./cotacoes/index";
import zapiCallbackRouter from "./zapi-callback";
import financeiroRouter from "./financeiro/index";
import integracoesRouter from "./integracoes/index";
import helenaRouter from "./helena/index";
import crmRouter from "./crm/index";
import automationRouter from "./automation/index";
import mcpRouter from "./mcp";
import internalN8nWorkflowsRouter from "./internal/n8n-workflows";
import internalTrafficRouter from "./internal/traffic";
import adminTrialLabRouter from "./admin-trial-lab";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(tenantsRouter);
router.use(appsRouter);
router.use(usersRouter);
router.use(kanbanRouter);
router.use(orcamentoRouter);
router.use(comunidadeRouter);
router.use(billingRouter);
router.use(chatRouter);
router.use(suporteRouter);
router.use(custosOrcamentosRouter);
router.use(custosFichasRouter);
router.use(storageRouter);
router.use(relatoriosRouter);
router.use(parceirosRouter);
router.use(webhooksVhsysRouter);
router.use(plmRouter);
router.use(feedbackRouter);
router.use(mentorRouter);
router.use(operationalEventsRouter);
router.use(atosRouter);
router.use(marketingRouter);
router.use(athosMemoryRouter);
router.use(metaRouter);
router.use(assistantRouter);
router.use(modaConectaRouter);
router.use(internalMarketingRouter);
router.use(internalCrmRouter);
router.use(internalLeadsRouter);
router.use(internalAutomationRouter);
router.use(internalLeadHandoffRouter);
router.use(internalGrowthRouter);
router.use(internalCreativeImageRouter);
router.use(internalLeadContextRouter);
router.use(internalZapiWebhookRouter);
router.use(internalZapiCaptureRouter);
router.use(internalLeadClassifyRouter);
router.use(internalLeadConversationStateRouter);
router.use(internalZapiPollStateRouter);
router.use(internalGptMakerRouter);
router.use(gptmakerWebhookRouter);
router.use(internalFidelizacaoRouter);
router.use(internalMetaSendRouter);
router.use(publicR2pbFormRouter);
router.use(publicR2pbOperacionalRouter);
router.use(publicFornecedorPageRouter);
router.use(internalR2pbLookupRouter);
router.use(internalR2pbZapiCheckRouter);
router.use(internalJourneyRouter);
router.use(internalAgentHandoffsRouter);
router.use(texintelRouter);
router.use(publicParceiroFormRouter);
router.use(publicRhFormRouter);
router.use(parceirosCrudRouter);
router.use(cotacoesRouter);
router.use(zapiCallbackRouter);
router.use(financeiroRouter);
router.use(integracoesRouter);
router.use(helenaRouter);
router.use(crmRouter);
router.use(automationRouter);
router.use(mcpRouter);
router.use(internalN8nWorkflowsRouter);
router.use(internalTrafficRouter);
router.use(adminTrialLabRouter);

// ── Teste: serve a landing page R2PB (temporário — remover após aprovação) ──
router.get("/test/landing-r2pb", (_req: Request, res: Response) => {
  try {
    const html = readFileSync(
      resolve(process.cwd(), "../../attached_assets/landing-r2pb-qualificacao.html"),
      "utf-8"
    );
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    res.send(html);
  } catch {
    res.status(404).send("Arquivo não encontrado");
  }
});

export default router;
