// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crm/CRMChat.tsx": () => import("../components/mockups/crm/CRMChat.tsx"),
  "./components/mockups/crm/CRMPipeline.tsx": () => import("../components/mockups/crm/CRMPipeline.tsx"),
  "./components/mockups/crm/CRMRelatorios.tsx": () => import("../components/mockups/crm/CRMRelatorios.tsx"),
  "./components/mockups/erp/ERPDashboard.tsx": () => import("../components/mockups/erp/ERPDashboard.tsx"),
  "./components/mockups/erp/ERPEstoque.tsx": () => import("../components/mockups/erp/ERPEstoque.tsx"),
  "./components/mockups/erp/ERPIntegracoes.tsx": () => import("../components/mockups/erp/ERPIntegracoes.tsx"),
  "./components/mockups/form-vibes/MidnightIndigo.tsx": () => import("../components/mockups/form-vibes/MidnightIndigo.tsx"),
  "./components/mockups/form-vibes/SlateIndustrial.tsx": () => import("../components/mockups/form-vibes/SlateIndustrial.tsx"),
  "./components/mockups/form-vibes/WarmEditorial.tsx": () => import("../components/mockups/form-vibes/WarmEditorial.tsx"),
  "./components/mockups/hub-variants/HubDark.tsx": () => import("../components/mockups/hub-variants/HubDark.tsx"),
  "./components/mockups/hub-variants/HubLight.tsx": () => import("../components/mockups/hub-variants/HubLight.tsx"),
  "./components/mockups/r2pb-referencia-cliente/CurrentKanbanCard.tsx": () => import("../components/mockups/r2pb-referencia-cliente/CurrentKanbanCard.tsx"),
  "./components/mockups/r2pb-referencia-cliente/CurrentOPPrint.tsx": () => import("../components/mockups/r2pb-referencia-cliente/CurrentOPPrint.tsx"),
  "./components/mockups/r2pb-referencia-cliente/ProposedKanbanCard.tsx": () => import("../components/mockups/r2pb-referencia-cliente/ProposedKanbanCard.tsx"),
  "./components/mockups/r2pb-referencia-cliente/ProposedOPPrint.tsx": () => import("../components/mockups/r2pb-referencia-cliente/ProposedOPPrint.tsx")
};
