import { pgTable, text, integer, jsonb, timestamp, uuid, date, numeric, boolean } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const campaignAssets = pgTable("campaign_assets", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull(),
  campaignId: text("campaign_id").notNull(),
  contentItemId: uuid("content_item_id"),
  assetType: text("asset_type").notNull().default("image"),
  storagePath: text("storage_path").notNull(),
  promptUsed: text("prompt_used"),
  status: text("status").notNull().default("ready"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const campaignPublications = pgTable("campaign_publications", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull(),
  campaignId: text("campaign_id").notNull(),
  contentItemId: uuid("content_item_id"),
  assetId: uuid("asset_id"),
  channel: text("channel").notNull().default("instagram"),
  caption: text("caption"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  status: text("status").notNull().default("scheduled"),
  externalPostId: text("external_post_id"),
  externalAccountId: text("external_account_id"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const campaignMetrics = pgTable("campaign_metrics", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull(),
  campaignId: text("campaign_id").notNull(),
  publicationId: uuid("publication_id"),
  channel: text("channel").notNull().default("instagram"),
  externalPostId: text("external_post_id"),
  metricDate: date("metric_date").notNull(),
  impressions: integer("impressions").default(0),
  reach: integer("reach").default(0),
  likes: integer("likes").default(0),
  comments: integer("comments").default(0),
  shares: integer("shares").default(0),
  saves: integer("saves").default(0),
  profileVisits: integer("profile_visits").default(0),
  linkClicks: integer("link_clicks").default(0),
  directMessages: integer("direct_messages").default(0),
  leadsGenerated: integer("leads_generated").default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const tenantAssets = pgTable("tenant_assets", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull(),
  filename: text("filename").notNull(),
  storagePath: text("storage_path").notNull(),
  mimetype: text("mimetype").notNull().default("image/jpeg"),
  sizeBytes: integer("size_bytes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const brandBlueprints = pgTable("brand_blueprints", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull().unique(),
  nomeMarca: text("nome_marca"),
  segmento: text("segmento"),
  descricao: text("descricao"),
  proposito: text("proposito"),
  promessa: text("promessa"),
  diferencial: text("diferencial"),
  publicoPrincipal: text("publico_principal"),
  dores: jsonb("dores").$type<string[]>().default([]),
  desejos: jsonb("desejos").$type<string[]>().default([]),
  tomDeVoz: text("tom_de_voz"),
  adjetivos: jsonb("adjetivos").$type<string[]>().default([]),
  estiloVisual: text("estilo_visual"),
  referenciasEsteticas: text("referencias_esteticas"),
  produtoPrincipal: text("produto_principal"),
  objetivoAtual: text("objetivo_atual"),
  // ── Identidade Visual ────────────────────────────────────────────────────────
  whatsapp: text("whatsapp").default(""),
  instagram: text("instagram").default(""),
  corPrimaria: text("cor_primaria").default("#2563eb"),
  logoUrl: text("logo_url"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const campaignBlueprints = pgTable("campaign_blueprints", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull(),
  nome: text("nome").notNull(),
  objetivo: text("objetivo"),
  produtoFoco: text("produto_foco"),
  promessaCentral: text("promessa_central"),
  problemaCentral: text("problema_central"),
  desejoCentral: text("desejo_central"),
  publicoPrincipal: text("publico_principal"),
  objecoes: jsonb("objecoes").$type<string[]>().default([]),
  angulos: jsonb("angulos").$type<string[]>().default([]),
  pilares: jsonb("pilares").$type<string[]>().default([]),
  ctaPrincipal: text("cta_principal"),
  direcaoCriativa: text("direcao_criativa"),
  status: text("status").notNull().default("rascunho"),
  // ── Scheduling ──────────────────────────────────────────────────────────────
  periodDays: integer("period_days").default(30),
  startDate: text("start_date"),
  autoScheduleEnabled: boolean("auto_schedule_enabled").default(true),
  autoPublishEnabled: boolean("auto_publish_enabled").default(false),
  defaultSlotTime: text("default_slot_time").default("09:00"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const campaignScheduleSlots = pgTable("campaign_schedule_slots", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  campaignBlueprintId: uuid("campaign_blueprint_id").notNull(),
  companySlug: text("company_slug").notNull(),
  creativeId: uuid("creative_id"),
  channel: text("channel"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(),
  slotOrder: integer("slot_order").notNull(),
  stageFocus: text("stage_focus"),
  status: text("status").notNull().default("empty"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const machineCreatives = pgTable("machine_creatives", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull(),
  campaignBlueprintId: uuid("campaign_blueprint_id").notNull(),
  modoCriativo: text("modo_criativo").notNull().default("conceitual"),
  canal: text("canal"),
  formato: text("formato"),
  objetivoPeca: text("objetivo_peca"),
  headline: text("headline"),
  hook: text("hook"),
  legenda: text("legenda"),
  cta: text("cta"),
  direcaoArte: text("direcao_arte"),
  promptVisual: text("prompt_visual"),
  composicaoSugerida: text("composicao_sugerida"),
  cores: text("cores"),
  elementosObrigatorios: text("elementos_obrigatorios"),
  elementosProibidos: text("elementos_proibidos"),
  proporcao: text("proporcao"),
  quantidadeVariacoes: integer("quantidade_variacoes").default(1),
  statusAprovacao: text("status_aprovacao").notNull().default("pendente"),
  brandFitScore: numeric("brand_fit_score", { precision: 4, scale: 1 }),
  campaignFitScore: numeric("campaign_fit_score", { precision: 4, scale: 1 }),
  commercialStrengthScore: numeric("commercial_strength_score", { precision: 4, scale: 1 }),
  visualQualityScore: numeric("visual_quality_score", { precision: 4, scale: 1 }),
  videoPrompt: text("video_prompt"),
  assetStoragePath: text("asset_storage_path"),
  imagePromptUsed: text("image_prompt_used"),
  brandingVariant: text("branding_variant").default("auto"),
  funnelStage: text("funnel_stage"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
  publicationId: uuid("publication_id"),
  templateUsed: text("template_used"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const contentPackItems = pgTable("content_pack_items", {
  id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
  companySlug: text("company_slug").notNull(),
  campaignId: text("campaign_id").notNull(),
  contentType: text("content_type").notNull(),
  title: text("title"),
  hook: text("hook"),
  caption: text("caption"),
  cta: text("cta"),
  funnelStage: text("funnel_stage"),
  scheduledDay: integer("scheduled_day"),
  scriptJson: jsonb("script_json"),
  imagePrompt: text("image_prompt"),
  status: text("status").notNull().default("pending"),
  statusNote: text("status_note"),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  scheduledDate: date("scheduled_date"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
