import { pgTable, uuid, varchar, text, boolean, timestamp, index } from "drizzle-orm/pg-core";

export const parceirosProducao = pgTable("parceiros_producao", {
  id:                  uuid("id").primaryKey().defaultRandom(),
  tenant_id:           varchar("tenant_id", { length: 50 }).notNull(),
  fornecedor_id:       varchar("fornecedor_id"), // FK lógica → fornecedores.id (transição)
  nome:                text("nome").notNull(),
  whatsapp:            varchar("whatsapp", { length: 20 }).notNull(),
  email:               text("email"),
  empresa:             text("empresa"),
  area:                text("area").notNull(),
  subtipo:             text("subtipo"),
  tipo_malha:          text("tipo_malha"),
  qtde_costureiros:    text("qtde_costureiros"),
  tipos_maquina:       text("tipos_maquina").array(),
  linha_produto:       text("linha_produto").array(),
  tipos_acabamento:    text("tipos_acabamento").array(),
  especialidades:      text("especialidades").array(),
  capacidade_produtiva:text("capacidade_produtiva"),
  private_label:       boolean("private_label").default(false),
  tipos_produto:       text("tipos_produto").array(),
  aceita_briefing:     boolean("aceita_briefing").default(true),
  estado:              varchar("estado", { length: 2 }),
  cidade:              text("cidade"),
  bairro:              text("bairro"),
  status:              text("status").notNull().default("prospecto"),
  obs:                 text("obs"),
  created_at:          timestamp("created_at").defaultNow(),
  updated_at:          timestamp("updated_at").defaultNow(),
}, (t) => [
  index("parceiros_producao_tenant_fornecedor_idx").on(t.tenant_id, t.fornecedor_id),
]);

export const candidatosRh = pgTable("candidatos_rh", {
  id:                    uuid("id").primaryKey().defaultRandom(),
  tenant_id:             varchar("tenant_id", { length: 50 }).notNull(),
  nome:                  text("nome").notNull(),
  whatsapp:              varchar("whatsapp", { length: 20 }).notNull(),
  email:                 text("email"),
  area:                  text("area").notNull(),
  funcao:                text("funcao"),
  experiencia:           text("experiencia"),
  disponibilidade:       text("disponibilidade"),
  experiencia_confeccao: boolean("experiencia_confeccao").default(false),
  resumo:                text("resumo"),
  estado:                varchar("estado", { length: 2 }),
  cidade:                text("cidade"),
  bairro:                text("bairro"),
  status:                text("status").notNull().default("novo"),
  obs:                   text("obs"),
  created_at:            timestamp("created_at").defaultNow(),
  updated_at:            timestamp("updated_at").defaultNow(),
});
